# Generated by Django 3.1 on 2021-01-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ettoday',
            name='news_time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
